<table width="100%">
  <tr>
    <td valign="top" width="50%">
		<h1>PHPSlickGrid Examples</h1>
		<p>Is an extension to the excellent <a href='https://github.com/mleibman/SlickGrid'>SlickGrid</a> component by <a href='https://github.com/mleibman'>Michael Leibman</a>.</p>
		<p>The goal of PHPSlickGrid is to make persistent complex grids simple by abstracting logic behind Zend Helpers and extensions to Zend Db Table.</p>
    </td>
    <td valign="top">
      <h2>Examples:</h2>
      <ul>
        <li><a href='example1'>Example 1</a> - A basic PHPSlickGrid with minimal configuration</li>
      </ul>
        <h2>View Source:</h2>
        <ul>
            <li><A href="https://github.com/jstormes/phpslickgriddemo/tree/master" target="_sourcewindow"> Get the source from Github</a></li>
        </ul>
    </td>
  </tr>
</table>