<style>
/* Active row highlight color */
.slick-row.active .slick-cell {
     background-color: #FFB;
}
</style>


<table width="100%">
  <tr>
    <td valign="top" width="50%">
    	<!-- Instantiate the PHPSlickGrid view helper -->
    	<?php echo $this->PHPSlickGrid($this->model,null,'width:600px;height:500px;'); ?>
    	<!-- End of code from the PHPSlickGrid view helper -->
    </td>
    <td valign="top">
      <h2>Demonstrates:</h2>
      <ul>
        <li>basic PHPSlickGrid with minimal configuration</li>
      </ul>
        <h2>View Source:</h2>
        <ul>
            <li><A href="https://github.com/mleibman/SlickGrid/blob/gh-pages/examples/example1-simple.html" target="_sourcewindow"> Get the source from Github</a></li>
        </ul>
    </td>
  </tr>
</table>